from .asset_routes import asset_routes
from .auth_routes import auth_routes
from .character_routes import character_routes
from .chronicle_routes import chronicle_routes
from .condition_routes import condition_routes
from .effect_routes import effect_routes
from .lock_routes import lock_routes
from .place_routes import place_routes
from .rank_routes import rank_routes
from .tale_routes import tale_routes
from .thread_routes import thread_routes
from .user_routes import user_routes