"""empty message

Revision ID: 01284f7f7f89
Revises: b5d5b4d1fa85
Create Date: 2020-12-09 12:59:50.030026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01284f7f7f89'
down_revision = 'b5d5b4d1fa85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('asset_effects', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=0)
    op.add_column('conditions', sa.Column('chronicle_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'conditions', 'chronicles', ['chronicle_id'], ['id'])
    op.add_column('ranks', sa.Column('chronicle_id', sa.Integer(), nullable=False))
    op.add_column('ranks', sa.Column('title', sa.String(length=50), nullable=False))
    op.create_foreign_key(None, 'ranks', 'conditions', ['chronicle_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ranks', type_='foreignkey')
    op.drop_column('ranks', 'title')
    op.drop_column('ranks', 'chronicle_id')
    op.drop_constraint(None, 'conditions', type_='foreignkey')
    op.drop_column('conditions', 'chronicle_id')
    op.alter_column('asset_effects', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
