"""empty message

Revision ID: b06e5c60a3c4
Revises: b5d5b4d1fa85
Create Date: 2020-12-09 03:59:13.123212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b06e5c60a3c4'
down_revision = 'b5d5b4d1fa85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('asset_effects', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=0)
    op.add_column('conditions', sa.Column('title', sa.String(length=50), nullable=False))
    op.drop_column('conditions', 'name')
    op.add_column('entities', sa.Column('title', sa.String(length=50), nullable=False))
    op.drop_column('entities', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entities', sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('entities', 'title')
    op.add_column('conditions', sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('conditions', 'title')
    op.alter_column('asset_effects', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
