"""empty message

Revision ID: a3668c3071bc
Revises: 875ef015d661
Create Date: 2020-12-04 13:35:24.293592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3668c3071bc'
down_revision = '875ef015d661'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('asset_effects', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=0)
    op.add_column('chronicles', sa.Column('title', sa.String(length=50), nullable=False))
    op.drop_column('chronicles', 'name')
    op.add_column('tales', sa.Column('title', sa.String(length=50), nullable=False))
    op.drop_column('tales', 'name')
    op.add_column('threads', sa.Column('description', sa.String(), nullable=False))
    op.drop_column('threads', 'body')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('threads', sa.Column('body', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('threads', 'description')
    op.add_column('tales', sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('tales', 'title')
    op.add_column('chronicles', sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('chronicles', 'title')
    op.alter_column('asset_effects', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
