"""Added thread_choices

Revision ID: 875ef015d661
Revises: aab03e0063a2
Create Date: 2020-12-03 23:12:10.308428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '875ef015d661'
down_revision = 'aab03e0063a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thread_choices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('current_thread_id', sa.Integer(), nullable=False),
    sa.Column('choice_thread_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['choice_thread_id'], ['threads.id'], ),
    sa.ForeignKeyConstraint(['current_thread_id'], ['threads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('thread_choice')
    op.alter_column('asset_effects', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=0)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('asset_effects', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_table('thread_choice',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('current_thread_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('choice_thread_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['choice_thread_id'], ['threads.id'], name='thread_choice_choice_thread_id_fkey'),
    sa.ForeignKeyConstraint(['current_thread_id'], ['threads.id'], name='thread_choice_current_thread_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='thread_choice_pkey')
    )
    op.drop_table('thread_choices')
    # ### end Alembic commands ###
