"""empty message

Revision ID: e6b4bc762641
Revises: 01284f7f7f89
Create Date: 2020-12-09 13:03:03.661482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6b4bc762641'
down_revision = '01284f7f7f89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('asset_effects', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=0)
    op.drop_column('ranks', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ranks', sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.alter_column('asset_effects', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
